name: Deploy OrionUI

on:
  push:
    branches: ["main"]

env:
  REGISTRY: git.tu-berlin.de:5000/zodiac/zodiac-meta

  IMAGE_NAME: orion-ui
  CONTEXT: .
  DOCKERFILE: ./Dockerfile

  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to our gitlab instance
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: github worker
          password: ${{ secrets.ZODIAC_CI_TOKEN }}
      - name: Set version
        run: echo "VERSION=0.${{ github.run_number }}.0-cicd" >> $GITHUB_ENV
      - name: Build and push docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          push: true
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
